name: dmj_stock_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  get: ^4.7.3
  pinput: ^5.0.1
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.9.0
  mobile_scanner: ^7.0.1
  flutter_svg: ^2.2.0
  barcode_image: ^2.0.3
  image: ^4.5.4
  printing: ^5.14.2
  pdf: ^3.11.3
  intl_phone_field: ^3.2.0
  drop_down_list: ^2.1.1
  country_state_city_pro: ^0.0.6
  syncfusion_flutter_xlsio: ^30.1.42
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  get_storage: ^2.1.1
  share_plus: 13.1.0
  smooth_page_indicator: ^2.0.1
  qr_flutter: ^4.1.0
  qr: ^3.0.2
  intl: ^0.19.0
  flutter_thermal_printer: 2.2.1
  screenshot: ^3.0.0
  device_info_plus: ^13.2.0
  url_launcher: ^6.3.2
  file_picker: ^12.2.0
  flutter_native_contact_picker: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - packages/country_state_city_pro/assets/country.json
    - packages/country_state_city_pro/assets/state.json
    - packages/country_state_city_pro/assets/city.json
